//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracGrup
    {
        public int AracGrup_ID { get; set; }
        public string AracGrup_Adi { get; set; }
        public int AracGrup_Status { get; set; }
        public Nullable<System.DateTime> AracGrup_CreateDate { get; set; }
    }
}
