//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracYakitTuru
    {
        public int AracYakitTuru_ID { get; set; }
        public string AracYakitTuru_Adi { get; set; }
        public int AracYakitTuru_Status { get; set; }
        public System.DateTime AracYakitTuru_CreateDate { get; set; }
    }
}
