//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracModel
    {
        public int AracModel_ID { get; set; }
        public int AracMarka_ID { get; set; }
        public string AracModel_Adi { get; set; }
        public Nullable<int> AracModel_Status { get; set; }
        public Nullable<System.DateTime> AracModel_CreateDate { get; set; }
    }
}
