//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracKasaTipi
    {
        public int AracKasaTipi_ID { get; set; }
        public string AracKasaTipi_Adi { get; set; }
        public int AracKasaTipi_Status { get; set; }
        public Nullable<System.DateTime> AracKasaTipi_CreateDate { get; set; }
    }
}
