//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariEhliyet
    {
        public int CariEhliyet_ID { get; set; }
        public Nullable<int> Cari_ID { get; set; }
        public Nullable<System.DateTime> CariEhliyet_VerilisTarihi { get; set; }
        public Nullable<System.DateTime> CariEhliyet_GecerlilikTarihi { get; set; }
        public string CariEhliyet_VerildigiYer { get; set; }
        public string CariEhliyet_DogumYeri { get; set; }
        public string CariEhliyet_EhliyetNumarasi { get; set; }
        public Nullable<int> EhliyetSinif_ID { get; set; }
        public Nullable<int> KanGrubu_ID { get; set; }
    }
}
