//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkstraHizmetler
    {
        public int EkstraHizmetler_ID { get; set; }
        public string EkstraHizmetler_Adi { get; set; }
        public Nullable<double> EkstraHizmetler_Ucreti { get; set; }
        public Nullable<int> EkstraHizmetler_Status { get; set; }
        public Nullable<System.DateTime> EkstraHizmetler_CreateDate { get; set; }
    }
}
