//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkSurucu
    {
        public int EkSurucu_ID { get; set; }
        public Nullable<int> Cari_ID { get; set; }
        public Nullable<System.DateTime> EkSurucu_CreateDate { get; set; }
        public int EkSurucu_Status { get; set; }
    }
}
