//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemEkstraHizmetler
    {
        public int IslemEkstraHizmetler_ID { get; set; }
        public Nullable<int> Islem_ID { get; set; }
        public Nullable<int> EkstraHizmetler_ID { get; set; }
        public Nullable<System.DateTime> IslemEkstraHizmetler_CreateDate { get; set; }
        public int IslemEkstraHizmetler_Status { get; set; }
    }
}
