//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KanGrubu
    {
        public int KanGrubu_ID { get; set; }
        public string KanGrubu_Adi { get; set; }
        public Nullable<int> KanGrubu_Status { get; set; }
        public Nullable<System.DateTime> KanGrubu_CreateDate { get; set; }
    }
}
