//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciRolIliskileri
    {
        public int RolIliski_ID { get; set; }
        public int Rol_ID { get; set; }
        public int Kullanici_ID { get; set; }
    }
}
