//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int Kullanici_ID { get; set; }
        public string Kullanici_TamAdi { get; set; }
        public string Kullanici_Adi { get; set; }
        public string Kullanici_Sifre { get; set; }
        public Nullable<System.DateTime> Kullanici_SonGirisZamani { get; set; }
        public Nullable<int> Kullanici_Status { get; set; }
        public Nullable<System.DateTime> Kullanici_CreateDate { get; set; }
    }
}
