//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokasyon
    {
        public int Lokasyon_ID { get; set; }
        public string Lokasyon_Adi { get; set; }
        public Nullable<int> Lokasyon_Tipi { get; set; }
        public Nullable<int> Lokasyon_Status { get; set; }
        public Nullable<System.DateTime> Lokasyon_CreateDate { get; set; }
    }
}
