//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServisFirma
    {
        public int ServisFirma_ID { get; set; }
        public string ServisFirma_Adi { get; set; }
        public string ServisFirma_Adres1 { get; set; }
        public string ServisFirma_Adres2 { get; set; }
        public string ServisFirma_Tel1 { get; set; }
        public string ServisFirma_Tel2 { get; set; }
        public string ServisFirma_Email { get; set; }
        public string ServisFirma_Yetkili { get; set; }
        public Nullable<System.DateTime> ServisFirma_CreateDate { get; set; }
        public int ServisFirma_Status { get; set; }
    }
}
