//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewServis
    {
        public int Servis_ID { get; set; }
        public string AracGrup_Adi { get; set; }
        public string AracMarka_Adi { get; set; }
        public string AracModel_Adi { get; set; }
        public string Arac_Yil { get; set; }
        public string AracPlakaNo { get; set; }
        public Nullable<System.DateTime> Servis_ServisZamani { get; set; }
        public string ServisFirma_Adi { get; set; }
        public string Servis_Notlar { get; set; }
        public Nullable<double> Servis_Ucreti { get; set; }
    }
}
