//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewIslem
    {
        public int Islem_ID { get; set; }
        public string IslemTipim { get; set; }
        public string Cari_AdSoyad { get; set; }
        public string AracGrup_Adi { get; set; }
        public string AracMarka_Adi { get; set; }
        public string AracModel_Adi { get; set; }
        public string Arac_Yil { get; set; }
        public Nullable<System.DateTime> Islem_BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> Islem_BitisTarihi { get; set; }
        public Nullable<int> Islem_IlkKM { get; set; }
        public Nullable<int> Islem_SonKM { get; set; }
        public Nullable<int> Islem_YakitDurumu { get; set; }
        public Nullable<int> Islem_TeslimatLokasyonID { get; set; }
        public Nullable<int> Islem_IadeLokasyonID { get; set; }
        public Nullable<double> Islem_GunlukUcret { get; set; }
        public Nullable<double> Islem_GunlukKMSiniri { get; set; }
        public Nullable<double> Islem_ToplamKiralamaUcreti { get; set; }
        public Nullable<double> Islem_ToplamKMAsimUcreti { get; set; }
        public Nullable<double> Islem_ToplamEkstraHizmetler { get; set; }
        public Nullable<double> Islem_ToplamValeHizmetleri { get; set; }
        public Nullable<double> Islem_ToplamDigerUcretler { get; set; }
        public Nullable<int> Islem_IskontoOrani { get; set; }
        public Nullable<double> Islem_TahsilEdilen { get; set; }
        public Nullable<double> Islem_KalanBorc { get; set; }
        public Nullable<int> Islem_Status { get; set; }
        public Nullable<System.DateTime> Islem_CreateDate { get; set; }
    }
}
