//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewAracList
    {
        public int Arac_ID { get; set; }
        public int Arac_Status { get; set; }
        public string AracGrup_Adi { get; set; }
        public string AracMarka_Adi { get; set; }
        public string AracModel_Adi { get; set; }
        public string Arac_Yil { get; set; }
        public string AracYakitTuru_Adi { get; set; }
        public string Arac_VitesTipi { get; set; }
        public string AracKasaTipi_Adi { get; set; }
        public string KlimaDurumu { get; set; }
        public string AracPlakaNo { get; set; }
        public double AracGuncelKM { get; set; }
        public string AracMotorNo { get; set; }
        public string AracSaseNo { get; set; }
        public string AracRuhsatSeriNo { get; set; }
        public string AracRenk_Adi { get; set; }
        public string KiralamaDurumu { get; set; }
        public Nullable<System.DateTime> Arac_TrafikSigortasiBitisTarihi { get; set; }
        public Nullable<System.DateTime> Arac_KaskoBitisTarihi { get; set; }
        public Nullable<System.DateTime> Arac_KoltukSigortasiBitisTarihi { get; set; }
        public Nullable<System.DateTime> Arac_FenniMuayeneGecerlilikTarihi { get; set; }
    }
}
