//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewCari
    {
        public int Cari_ID { get; set; }
        public int Cari_Status { get; set; }
        public string Cari_AdSoyad { get; set; }
        public string CariUyruk_Adi { get; set; }
        public string Cari_IDNumber { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> Cari_DogumTarihi { get; set; }
        public string Cari_EpostaAdresi { get; set; }
        public string Cari_Adres1 { get; set; }
        public string Cari_Adres2 { get; set; }
        public string CariSehir_Adi { get; set; }
        public string Cari_MobilTelefon { get; set; }
        public string Cari_LokalTelefon { get; set; }
        public Nullable<System.DateTime> Cari_CreateDate { get; set; }
    }
}
